- name: Connect AWS
  hosts: localhost
  gather_facts: true
  vars:
   ansible_connection: local
  tasks:
  - include_role:
      name: aws-vpc
  - include_role:
      name: ec2_windows_ami-0f25b344af3f73199 
