---
# tasks file for roles/ec2_windows_setup
- name: Set Timezone
  win_timezone:
    timezone: Pacific Standard Time

- name: Change Region
  win_region:
    location: 244
    format: en-US
    unicode_language: en-US
  register: result

- name: Change Region - Reboot
  win_reboot:
  when: result.restart_required

- name: Windows Update
  win_updates:
    reboot: true
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups