---
# tasks file for roles/ec2_windows_ami-0f25b344af3f73199
- name: find vpc id for sg object "{{ aws_security_group_name }}"
  ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:environment": "{{ aws_environment_identifier }}"
  register: vpc_net_info_output

- set_fact:
    vpc_id_fact: "{{ vpc_net_info_output.vpcs[0].id }}"

- ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ vpc_id_fact }}"
  register: ec2_vpc_subnet_info_output

- debug: var=ec2_vpc_subnet_info_output.subnets.id

- name: find security group id for ec2 instance "{{ aws_instance_type }}"
  ec2_group_info:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc_id_fact }}"
      "tag:environment": "{{ aws_environment_identifier }}"
  register: ec2_group_info_output

- set_fact:  
    security_group_id_fact: "{{ ec2_group_info_output.security_groups[0].group_id }}"

- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: "{{ aws_ec2_key_name }}"
    region: "{{ aws_region }}"
  register: ec2_key_output      

- name: Save private key
  copy: content="{{ ec2_key_output.key.private_key }}" dest="./aws.key.pem" mode=0600
  when: ec2_key_output.changed