---
# tasks file for roles/ec2_security_group
- name: find vpc id for sg object "{{ object_tag_identifier }}"
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:environment": test
  register: vpc_net_info_output

- debug: var=item
  with_items: vpc_net_info_output.vpcs 

- name: ensure security group is present
  ec2_group:
    state: present
    name: "{{ ec2_group_name }}"
    description: Inbound WinRM and RDP
    vpc_id: "{{ item.id }}"
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 5986
      to_port: 5986
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 3389
      to_port: 3389
      cidr_ip: 0.0.0.0/0
      rules_egress:
    - proto: -1
      cidr_ip: 0.0.0.0/0
  register: sg_output