---
# tasks file for roles/ec2_security_group
- name: ensure security group is present
  ec2_group:
    name: "{{ ec2_group_name }}"
    description: Inbound WinRM and RDP
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 5986
      to_port: 5986
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 3389
      to_port: 3389
      cidr_ip: 0.0.0.0/0
      rules_egress:
    - proto: -1
      cidr_ip: 0.0.0.0/0
  register: sg_output