- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: 10.10.0.0/16
    region: "{{ region }}"
    state: present
    tags:
        name: ec2_vpc_name
        environment: test
  register: vpc_output

- name: Create EC2 vpc subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_output.vpc.id }}"
    region: "{{ region }}"
    state: present
    cidr: 10.10.0.0/16
    resource_tags:
        environment: test
  register: vpc_subnet_output