- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: 10.10.0.0/16
    region: "{{ region }}"
    tags:
        name: ec2_vpc_name
        environment: test
  register: vpc_output