- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: 10.10.0.0/16
    region: "{{ region }}"
    tags:
        name: ec2_vpc_name
        environment: test
  register: vpc_output

#- set_fact:
#    set_ec2_vpc_id: "{{ vpc_output.vpc-id }}"

- name: Create subnet for database servers
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_output.vpc-id }}"
    cidr: 10.10.0.0/16
    tags:
        name: ec2_vpc_subn_name
        environment: test
  register: vpc_subnet_output