- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{ aws_vpc_name }}"
    cidr_block: "{{ aws_cidr }}"
    region: "{{ aws_region }}"
    state: present
    tags:
        name: "{{ aws_vpc_name }}"
        environment: "{{ aws_environment_identifier }}"
        owner: aws_ansible_iam_role
  register: vpc_output