---
# tasks file for roles/aws_ec2_linux_instance
- name: find vpc id for ec2 instance in environment "{{ aws_environment_identifier }}" and region "{{ aws_region }}"
  ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:environment": "{{ aws_environment_identifier }}"
  register: vpc_net_info_output

- set_fact:
    vpc_id_fact: "{{ vpc_net_info_output.vpcs[0].id }}"

- name: find vpc subnet id for vpc in environment "{{ aws_environment_identifier }}" and region "{{ aws_region }}"
  ec2_vpc_subnet_info:
    region: "{{ aws_region }}"
    filters:
      "tag:environment": "{{ aws_environment_identifier }}"
  register: ec2_vpc_subnet_info_output

- set_fact:
    vpc_subnet_id_fact: "{{ ec2_vpc_subnet_info_output.subnets[0].id }}"

- name: find security group id in environment "{{ aws_environment_identifier }}" and region "{{ aws_region }}"
  ec2_group_info:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc_id_fact }}"
      "tag:environment": "{{ aws_environment_identifier }}"
  register: ec2_group_info_output

- set_fact:  
    security_group_id_fact: "{{ ec2_group_info_output.security_groups[0].group_id }}"

- name: create a new ec2 pub key for new ec 2 instance in evironment "{{ aws_environment_identifier }}" and region "{{ aws_region }}"
  ec2_key:
    name: "{{ aws_ec2_key_name }}"
    region: "{{ aws_region }}"
    key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8Xvsh1tx6ZStdeOmZOdfyjlEIEaHqP83F2Mw+E4BehpAuAYJQpLmEN5D4/5hTnf0v1BV8ZMviGfynrfDX1Tg8tGFlrnDS7qQdNPfRWAf2o9kgdht2nnGFBAMiCQ6gBNHE4i4KfzhYZzrEqFQzb4JFxQ2NcBcH/hPFpDeFc1rJTZaijR2Fd+snhiNtfhKPtDU6INI8QGx7PFhJUZAQQly6/QXEiRsHvAKfiv0TBTrKhd6DujabN2Ot0R1bFTewxqtgUs03/owpLJ1OkDhKjhWfXkocoZxy43g8M5XuEiI2t8Ry8CyR4CRqf0/t2ITxyZNIYMehZJc5wKSF+doCExPv/k+fbHUSHUJthnXp7QX1NBhqwDcY/qG7beawOCOgt/UfOflPoDaUh5tSh3pMbB68SmdSncxy+L+G12cs3DK6A5CtxDCu/3R3Divzz7cP97MgwUyTO9r/PIsUhKzdSMB8nnirrlCvTtXNBakmC/voPeVEWVyakeHPU+l9aj1VaTs= hvanderm@hvanderm.remote.csb'
  register: ec2_key_output      

- name: Create an EC2 instance
  ec2_instance:
    id: "{{ aws_ec2_instance_name }}"
    key_name: "{{ aws_ec2_key_name }}"
    region: "{{ aws_region }}"
    security_group: "{{ security_group_id_fact }}"
    instance_type: "{{ aws_instance_type }}"
    image_id: "{{ aws_ami_image_id }}"
    wait: yes
    wait_timeout: 500
    instance_tags:
      instance_name: "{{ aws_ec2_instance_name }}"
      environment: "{{ aws_environment_identifier }}"
      operating_system: "{{ aws_os_type }}"
      ami_id: "{{ aws_ami_image_id }}"
      owner: "{{ aws_ansible_iam_role }}"
      group: "{{ security_group_id_fact }}"
    monitoring: yes  
    name: "{{ instance_name }}"
    register: ec2