---
# tasks file for roles/aws_vpc_subnet
- name: find vpc id for sg object "{{ aws_security_group_name }}"
  ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:environment": "{{ aws_environment_identifier }}"
  register: vpc_net_info_output

- set_fact:
    vpc_id_fact: "{{ vpc_net_info_output.vpcs[0].id }}"

- name: Create VPC subnet and attach to "{{ vpc_id_fact }}"
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id_fact }}"
    region: "{{ aws_region }}"
    state: present
    cidr: "{{ aws_cidr }}"
    resource_tags:
        environment: "{{ aws_environment_identifier }}"
        owner: "{{ aws_ansible_iam_role }}"
  register: vpc_subnet_output